.PHONY: clean All

All:
	@echo "----------Building project:[ unordered - Debug ]----------"
	@$(MAKE) -f  "unordered.mk"
clean:
	@echo "----------Cleaning project:[ unordered - Debug ]----------"
	@$(MAKE) -f  "unordered.mk" clean
