{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'bgTemplate',
          'title':'Standard Template with File->Exit menu',
          'size':(646, 960),
          'style':['resizeable'],

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit',
                   'command':'exit',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'Button', 
    'name':'luckyNumbers', 
    'position':(250, 571), 
    'size':(152, 111), 
    'enabled':False, 
    'font':{'faceName': u'MS Shell Dlg 2', 'family': 'sansSerif', 'size': 14}, 
    'label':u'Lucky Numbers', 
    'visible':False, 
    },

{'type':'Image', 
    'name':'MegaBall', 
    'position':(530, 322), 
    'size':(100, 100), 
    'file':'', 
    'visible':False, 
    },

{'type':'Image', 
    'name':'Ball5', 
    'position':(425, 321), 
    'size':(100, 100), 
    'file':'', 
    'visible':False, 
    },

{'type':'Image', 
    'name':'Ball4', 
    'position':(321, 321), 
    'size':(100, 100), 
    'file':'', 
    'visible':False, 
    },

{'type':'Image', 
    'name':'Ball3', 
    'position':(215, 322), 
    'size':(100, 100), 
    'file':'', 
    'visible':False, 
    },

{'type':'Image', 
    'name':'Ball2', 
    'position':(109, 322), 
    'size':(100, 100), 
    'file':'', 
    'visible':False, 
    },

{'type':'Image', 
    'name':'Ball1', 
    'position':(4, 323), 
    'size':(100, 100), 
    'file':'', 
    'visible':False, 
    },

{'type':'TextArea', 
    'name':'TextArea1', 
    'position':(64, 10), 
    'size':(508, 396), 
    'enabled':False, 
    'font':{'faceName': u'MS Shell Dlg 2', 'family': 'sansSerif', 'size': 18}, 
    'visible':False, 
    },

{'type':'Button', 
    'name':'BACK', 
    'position':(496, 800), 
    'size':(105, 76), 
    'enabled':False, 
    'font':{'faceName': u'MS Shell Dlg 2', 'family': 'sansSerif', 'size': 18}, 
    'label':u'BACK', 
    'visible':False, 
    },

{'type':'Button', 
    'name':'HOME', 
    'position':(387, 800), 
    'size':(105, 76), 
    'enabled':False, 
    'font':{'faceName': u'MS Shell Dlg 2', 'family': 'sansSerif', 'size': 18}, 
    'label':u'HOME', 
    'visible':False, 
    },

{'type':'Button', 
    'name':'tick10', 
    'position':(250, 436), 
    'size':(152, 111), 
    'enabled':False, 
    'font':{'faceName': u'MS Shell Dlg 2', 'family': 'sansSerif', 'size': 18}, 
    'label':u'10', 
    'visible':False, 
    },

{'type':'Button', 
    'name':'tick5', 
    'position':(250, 306), 
    'size':(152, 111), 
    'enabled':False, 
    'font':{'faceName': u'MS Shell Dlg 2', 'family': 'sansSerif', 'size': 18}, 
    'label':u'5', 
    'visible':False, 
    },

{'type':'Button', 
    'name':'tick1', 
    'position':(250, 169), 
    'size':(152, 111), 
    'enabled':False, 
    'font':{'faceName': u'MS Shell Dlg 2', 'family': 'sansSerif', 'size': 18}, 
    'label':u'1', 
    'visible':False, 
    },

{'type':'Button', 
    'name':'PowerBallbutton', 
    'position':(250, 436), 
    'size':(152, 111), 
    'font':{'faceName': u'MS Shell Dlg 2', 'family': 'sansSerif', 'size': 18}, 
    'label':u'PowerBall', 
    },

{'type':'Button', 
    'name':'MegaMillionsbutton', 
    'position':(250, 306), 
    'size':(152, 111), 
    'font':{'faceName': u'MS Shell Dlg 2', 'family': 'sansSerif', 'size': 18}, 
    'label':u'MegaMillions', 
    },

{'type':'Button', 
    'name':'SuperLottobutton', 
    'position':(250, 169), 
    'size':(152, 111), 
    'font':{'faceName': u'MS Shell Dlg 2', 'family': 'sansSerif', 'size': 18}, 
    'label':u'SuperLotto', 
    },

] # end components
} # end background
] # end backgrounds
} }
